### ISSUE TITLE
'ProcessorPerformanceLevel' does not exist in the type 'OVRManager' after migration to v2.8.0

### ISSUE THREAD

**Issue by abhilashca** [microsoft/MixedRealityToolkit-Unity#10828]
## Describe the bug

Migration from v2.7.3 to v2.8.0 using MR Feature Tool resulted in compile time error as - `Library\PackageCache\com.microsoft.mixedreality.toolkit.foundation@9e95381a667f-1659615280629\Providers\Oculus\XRSDK\OculusXRSDKDeviceManagerProfile.cs(131,27): error CS0426: The type name 'ProcessorPerformanceLevel' does not exist in the type 'OVRManager'`

![image](https://user-images.githubusercontent.com/12084395/182850122-28c14ea3-4c1b-454f-ac56-0d35fae40fcd.png)

## To reproduce

1. Unity project with MRTK v2.7.3
2. Launch MR Feature Tool and try to migrate to v2.8.0
3. Get's compile time error - `The type name 'ProcessorPerformanceLevel' does not exist in the type 'OVRManager'`.

## Expected behavior

Unity project should build fine after migration

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.14f1]
- MRTK Version [e.g. v2.7.3]

## Target platform (please complete the following information)

- Oculus Quest

**Comment by MaxWang-MS** [comment]
Hi @abhilashca, can you let us know what version of the Oculus Integration package you are using?

**Comment by abhilashca** [comment]
Here is what I am using

![image](https://user-images.githubusercontent.com/12084395/183011648-6cde6da7-2cdd-4901-8987-032d39d22ab9.png)

![image](https://user-images.githubusercontent.com/12084395/183011682-a7611295-87bf-4d12-8566-620293083c10.png)

I tried re-importing the package again, but didn't helped.

**Comment by ProfDru** [comment]
Also experiencing this issue

**Comment by RogPodge** [comment]
Hey there,

I'm testing this in our project with Oculus Integration 42.0 and am not seeing this issue. MRTK2 was tested to work as of Oculus 39.0, where they introduced the new performance level variable

https://developer.oculus.com/reference/unity/v39/class_o_v_r_manager/#a6ec677bb216ae0ad4e62bff3fd8bdadf

Their documentation for v39 shows that it's still in their API, as does the documentation for v42
https://developer.oculus.com/reference/unity/v39/class_o_v_r_manager/#a6ec677bb216ae0ad4e62bff3fd8bdadf
https://developer.oculus.com/reference/unity/v42/class_o_v_r_manager/

Could it be that the Oculus Integration Package needs to be updated to the latest?

**Comment by abhilashca** [comment]
@RogPodge My scenario was little different. I was upgrading the project from MRTK v2.5.3 to v2.8.0 steps by step. The upgrade went smooth till version v2.7.3 but got the error when I upgraded from v2.7.3 to v2.8.0.

Thanks for sharing the link for Oculus Integration v42. Let me try adding the same one more time and see what happens.

Will keep you posted in next couple of days.

Thank you.

**Comment by Zee2** [comment]
Closing as external API change; please reopen if the issue is not resolved.
