### ISSUE TITLE
Magic Leap Integration not working

### ISSUE THREAD

**Issue by AdrianDot** [microsoft/MixedRealityToolkit-Unity#8902]
## Describe the bug
After following the steps from the "**How to Configure Leap Motion (by Ultraleap) Hand Tracking in MRTK**" Guide Unity shows two Error-Messages :

"_Assets\Plugins\LeapMotion\Core\Scripts\LeapXRServiceProvider.cs(240,36): error CS0234: The type or namespace name 'SpatialTracking' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?_)"

and

"_Assets\Plugins\LeapMotion\Core\Scripts\LeapXRServiceProvider.cs(241,45): error CS0234: The type or namespace name 'SpatialTracking' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)_"

**Steps to reproduce the behavior:**

1. Follow the already mentioned guide to setup a Leap Motion for Unity.
2. Usually happens as soon as i import Leap Motion Unity Modules (Step 1.3 in the Guide from Github from the MRTK).
But also occures, when i try to integrate the Leap Motion Unity Modules with MRTK (Step 2.1)

## Your setup (please complete the following information)

- Unity Version [2019.4.12f1]
- Unity Version [2018.4.15f1]
- MRTK Version [e.g. v2.5.1]

and 

- Unity Version [2019.4.12f1]
- MRTK Version [e.g. v2.5]

## Additional context

I tried importing ARFoundation and it solved the error-messages for a moment till i tried to hit the playbutton.

I checked the scirpts which cause the error messages and (as expected) they´re just do not register UnityEngine._SpatialTracking_.

I am glad for any kind of help,
Adrian

**Comment by CDiaz-MS** [comment]
Hi @AdrianDot which version of the Leap Motion Unity Modules are you using?  Only 4.5.0 and 4.5.1 are currently supported.

**Comment by AdrianDot** [comment]
Oh wow, that was exactly what was wrong! When i downloaded the Leap Motion Unity Modules i was only offered the version 4.6.0. I had to reach out for the github releases to download the right version.

So, it definitely worked with Unity Version 2019.4.12f1 + MRTK 2.5.1 + Magic Leap Unity Modules 4.5.1.

Thanks alot @CDiaz-MS  for your help! Its the first time posting an issue on github for me and you already made this a good experience.
