### ISSUE TITLE
The type or namespace name Windows  does not exist in the namespace Microsoft

### ISSUE THREAD

**Issue by tletie** [microsoft/MixedRealityToolkit-Unity#10386]
## Describe the bug

After update to 2.7.2 version, it play nicely in Unity. However when make a build from Unity to Hololens 2, I have following errors:
1.Assets\MRTK\Providers\WindowsMixedReality\Shared\WindowsMixedRealityReprojectionUpdater.cs(56,57): error CS0234: The type or namespace name 'Windows' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
2. Assets\MRTK\Providers\WindowsMixedReality\Shared\WindowsMixedRealityUtilities.cs(12,17): error CS0234: The type or namespace name 'Windows' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
3. Assets\MRTK\Providers\WindowsMixedReality\Shared\WindowsMixedRealityUtilities.cs(126,23): error CS0246: The type or namespace name 'HolographicFrame' could not be found (are you missing a using directive or an assembly reference?)

## To reproduce

From Unity go to File => Build Settings.. => Universal Windows Platform =>Build as D3D, ARM => Click Build
The above errors are shown

## Expected behavior

It should be without any issue
## Your setup (please complete the following information)

- Unity 2018.4.32.f1
- MRTK v2.7.2

## Target platform (please complete the following information)
- HoloLens 2

**Comment by keveleigh** [comment]
Hello! Do you happen to have (or used to have) the DotNetWinRT package installed? We have some info on that at https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/features/tools/holographic-remoting?view=mrtkunity-2021-05#legacy-xr-setup-instructions

If you don't have it installed, you may accidentally have the define still set. You can find it and remove it via the steps at https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/features/tools/holographic-remoting?view=mrtkunity-2021-05#dotnetwinrt_present-define-written-into-player-settings

**Comment by tletie** [comment]
Hi @keveleigh, that fix the issue. I don't have DotNetWinRT. Installed it solve the issue.
Thank you

**Comment by keveleigh** [comment]
Glad to hear you got it sorted!
